// UI Utility file for shared icons, constants, and helper functions

// Pre-import common Material-UI icons
import {
  Add as AddIcon,
  Remove as RemoveIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Save as SaveIcon,
  Cancel as CancelIcon,
  Check as CheckIcon,
  Close as CloseIcon,
  Search as SearchIcon,
  FilterList as FilterIcon,
  Refresh as RefreshIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Share as ShareIcon,
  Favorite as FavoriteIcon,
  FavoriteBorder as FavoriteBorderIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Settings as SettingsIcon,
  Home as HomeIcon,
  Person as PersonIcon,
  Email as EmailIcon,
  Phone as PhoneIcon,
  LocationOn as LocationIcon,
  Event as CalendarIcon,
  AccessTime as ClockIcon,
  ArrowBack as ArrowBackIcon,
  ArrowForward as ArrowForwardIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
} from '@mui/icons-material';

// Icon mapping object
export const ICON_MAP = {
  add: AddIcon,
  remove: RemoveIcon,
  edit: EditIcon,
  delete: DeleteIcon,
  save: SaveIcon,
  cancel: CancelIcon,
  check: CheckIcon,
  close: CloseIcon,
  search: SearchIcon,
  filter: FilterIcon,
  refresh: RefreshIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  share: ShareIcon,
  favorite: FavoriteIcon,
  favoriteBorder: FavoriteBorderIcon,
  visibility: VisibilityIcon,
  visibilityOff: VisibilityOffIcon,
  settings: SettingsIcon,
  home: HomeIcon,
  person: PersonIcon,
  email: EmailIcon,
  phone: PhoneIcon,
  location: LocationIcon,
  calendar: CalendarIcon,
  clock: ClockIcon,
  arrowBack: ArrowBackIcon,
  arrowForward: ArrowForwardIcon,
  expandMore: ExpandMoreIcon,
  expandLess: ExpandLessIcon,
} as const;

export type IconName = keyof typeof ICON_MAP; 